### ISSUE TITLE
CookieCover only works for the first cover 

### ISSUE THREAD

**Issue by schmidex** [ddm-studio/cookie-byte#2]
I have multiple covers for the same handle on one page. Clicking the "accept cookie" button on the cover only hides the first cover.

The problem seems to be here:
`https://github.com/ddm-studio/cookie-byte/blob/main/resources/js/cookie-covers.js#L32`
Because the hiding is done by id

**Comment by ddm-dano** [comment]
Thanks for pointing it out, looked at it and could no longer reproduce the problem. Added another feature as well.

Feel free to write to me if there is anything else that is causing you problems.

**Comment by schmidex** [comment]
Still the same problem :-(
If you add multiple covers with the same handle.

Simple example:
I have a cover with the handle "youtube" that is added on multiple positions at the same page (using `{{ cookie_cover handle="youtube" }}`).

So I get multiple div containers with the same `id`
`<div class="ddm ddmcc" id="youtube" data-categories="thirdparty" style="display:block;opacity:100;">`

So the `hideConsented()` method in `cookie-covers.js` doesn't work.

**Comment by ddm-dano** [comment]
Oh, I'm sorry, I misunterstood your initial problem you had and thought the error was that the other covers with different handles but the same cookie categories were not hidden. But that was not what you meant at all.

I have now looked into the problem you've faced, that when you click on the "Accept cookies" button it would only hide the first only found on the page. This bug is now fixed, because it doesn't only select the first one but all with the same handle.

I hope this solves your problem finally and I'm sorry for the trouble. Please close this issue as soon as the bug is fixed, just to be sure. Also mind the warning in the release notes for v1.0.6: If you have any custom styling going on, you need to replace all instances of "**#**ddmcc-button-accept" to "**.**ddmcc-button-accept".

**Comment by schmidex** [comment]
Sorry for being unclear... English is not my native language
Works perfect now.
